### ISSUE TITLE
The workflow cancelled by itself 

### ISSUE THREAD

**Issue by DelmarHuang** [richartkeil/notion-guardian#4]
Hi, thank you for your work! I am an ordinary user, I don't code so I don't know how to fix this. I followed all your steps and I trigged the workflow three times by modifying the README and they all stopped here after repeating "exported 302 pages" 352 lines. Is here any solution? Thanks! I didn't do anything during the process of the backup workflow.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54244063/157524777-67eb4ed8-b8aa-4aad-99fd-c16ce9d100f3.png">

**Comment by DelmarHuang** [comment]
> Hi, thank you for your work! I am an ordinary user, I don't code so I don't know how to fix this. I followed all your steps and I trigged the workflow three times by modifying the README and they all stopped here after repeating "exported 302 pages" 352 lines. Is here any solution? Thanks! I didn't do anything during the process of the backup workflow.
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/54244063/157524777-67eb4ed8-b8aa-4aad-99fd-c16ce9d100f3.png">

**Comment by BartMistrot** [comment]
@DelmarHuang it's not currently working because of a high severity security vulnerability. The repo needs to do a quick merge for two pull requests regarding axios and the follow-redirects. I updated mine and it worked immediately after. 

Since you mentioned you don't code it would be best for you to wait for @richartkeil to update the repo so you can then get the updated files. The owner should be able to see the owner-specific pull requests sent by dependabot.

Hope that helps!

**Comment by DelmarHuang** [comment]
> @DelmarHuang it's not currently working because of a high severity security vulnerability. The repo needs to do a quick merge for two pull requests regarding axios and the follow-redirects. I updated mine and it worked immediately after.
> 
> Since you mentioned you don't code it would be best for you to wait for @richartkeil to update the repo so you can then get the updated files. The owner should be able to see the owner-specific pull requests sent by dependabot.
> 
> Hope that helps!

Thank you for the explanation! Get it now, I'll just wait hahah @BartMistrot

**Comment by richartkeil** [comment]
Thanks for bringing this up. You should be able to fetch and merge from this upstream repository to receive the newest changes. Also make sure to include your `notion_user_id` as a `NOTION_USER_ID` secret, since this is required to access exports by Notion now. You can obtain this id the same way as you obtained the `token_v2`, simply by checking the stored cookies on notion.so.

**Comment by DelmarHuang** [comment]
Done and thanks!
